git:
  submodules: false

# permissions
sudo: false

# Enable C++ support
language: cpp

# Compiler selection
dist: bionic

matrix:
  include:
    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=0
        - CC=clang-10
        - CXX=clang++-10
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-bionic-10
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['cmake', 'ninja-build', 'clang-10', 'clang++-10', 'lld-10', 'libc++-10-dev', 'libc++abi-10-dev']

    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=1
        - CC=clang-10
        - CXX=clang++-10
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-bionic-10
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['cmake', 'ninja-build', 'clang-10', 'clang++-10', 'lld-10', 'libc++-10-dev', 'libc++abi-10-dev']

    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=0
        - CC=gcc-10
        - CXX=g++-10
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-bionic-10
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['cmake', 'ninja-build', 'gcc-10', 'g++-10']

    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=1
        - CC=gcc-10
        - CXX=g++-10
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-bionic-10
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['cmake', 'ninja-build', 'gcc-10', 'g++-10']

script:
  - $CC --version
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DIHFT_STATIC_LINK=${STATIC_LINK} ..
  - cmake --build .
  - ctest -R
