git:
  submodules: false

# permissions
sudo: false

# Enable C++ support
language: cpp

# Compiler selection
dist: bionic

addons:
  apt:
    packages:
      - cmake
      - ninja-build

matrix:
  include:
    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=0
        - CC=clang-9
        - CXX=clang++-9
      os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['clang-9', 'clang++-9', 'lld-9', 'libc++-9-dev', 'libc++abi-9-dev']

    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=1
        - CC=clang-9
        - CXX=clang++-9
      os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['clang-9', 'clang++-9', 'lld-9', 'libc++-9-dev', 'libc++abi-9-dev']

    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=0
        - CC=gcc-9
        - CXX=g++-9
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['gcc-9', 'g++-9']

    - env:
        - BUILD_TYPE=Release
        - STATIC_LINK=1
        - CC=gcc-9
        - CXX=g++-9
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['gcc-9', 'g++-9']

script:
  - $CC --version
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DIHFT_STATIC_LINK=${STATIC_LINK} ..
  - cmake --build .
