# Check the OS type.

if(UNIX)
    STRING(REGEX MATCH "Linux" PROJECT_OS_LINUX ${CMAKE_SYSTEM_NAME})
endif()

if(APPLE)
    STRING(REGEX MATCH "Darwin" PROJECT_OS_OSX ${CMAKE_SYSTEM_NAME})
endif(APPLE)

message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")

# 32 or 64 bit
if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
    SET(PROJECT_PROC_64BIT TRUE BOOL INTERNAL)
    MESSAGE(STATUS "x86_64 cpu Detected")
endif()
