# Check the OS type.

IF(UNIX)
    STRING(REGEX MATCH "Linux" PROJECT_OS_LINUX ${CMAKE_SYSTEM_NAME})
ENDIF(UNIX)

IF(APPLE)
    STRING(REGEX MATCH "Darwin" PROJECT_OS_OSX ${CMAKE_SYSTEM_NAME})
ENDIF(APPLE)

message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")

# 32 or 64 bit
IF(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
    SET(PROJECT_PROC_64BIT TRUE BOOL INTERNAL)
    MESSAGE(STATUS "x86_64 cpu Detected")
ENDIF()
