name: linux-clang-x64-asan-ubsan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cloud-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up clang
      uses: egor-tensin/setup-clang@v1
      with:
       version: 20
       platform: x64
    - name: install-tools
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build clang-20 clang++-20 lld-20 libc++-20-dev libc++abi-20-dev libunwind-20-dev libclang-rt-20-dev
    - name: build
      env:
        CC: clang-20
        CXX: clang++-20
        TYPE: Release
      run: |
        $CC --version
        $CXX --version
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${TYPE} -DIHFT_SANITIZER_ADDRESS=1 -DIHFT_SANITIZER_UB=1 ..
        cmake --build .
    - name: test
      run: cd build && ctest
