name: linux-clang-x64
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cloud-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up clang
      uses: egor-tensin/setup-clang@v1
      with:
       version: 16
       platform: x64
    - name: install-tools
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build clang-16 clang++-16 lld-16 libc++-16-dev libc++abi-16-dev libunwind-16-dev libclang-rt-16-dev
    - name: build
      env:
        CC: clang-16
        CXX: clang++-16
        TYPE: Release
      run: |
        $CC --version
        $CXX --version
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${TYPE} ..
        cmake --build .
    - name: test
      run: cd build && ctest -R
    - name: info
      run: cd build && ./platform_get_info
