name: linux-clang-x64-static
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cloud-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install-tools
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build clang-12 clang++-12 lld-12 libc++-12-dev libc++abi-12-dev
    - name: build
      env:
        CC: clang-12
        CXX: clang++-12
        TYPE: Release
      run: |
        $CC --version
        $CXX --version
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${TYPE} -DIHFT_LINK_STATIC=1 ..
        cmake --build .
    - name: test
      run: cd build && ctest -R
    - name: info
      run: cd build && ./platform_get_info
