name: macos-x64-tsan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
jobs:
  cloud-ci:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: install-tools
      run: brew install cmake ninja
    - name: build
      env:
        CC: clang
        CXX: clang++
        TYPE: Release
      run: |
        $CC --version
        $CXX --version
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${TYPE} -DIHFT_SANITIZER_THREAD=1 ..
        cmake --build .
    - name: test
      run: cd build && ctest
