name: macos-x64-asan-ubsan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install-tools
      run: brew install cmake ninja
    - name: build
      env:
        CC: clang
        CXX: clang++
        TYPE: Release
      run: |
        $CC --version
        $CXX --version
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${TYPE} -DIHFT_SANITIZER_ADDRESS=1 -DIHFT_SANITIZER_UB=1 ..
        cmake --build .
    - name: test
      run: cd build && ctest -R

